# Generated by Django 3.0 on 2020-01-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personas', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('hora_in', models.TimeField()),
                ('hora_out', models.TimeField()),
            ],
        ),
    ]
